package Client;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.net.Socket;
import java.sql.*;
import javax.swing.JOptionPane;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;
import shared.*;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.plaf.multi.MultiLookAndFeel;

public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private static final String SERVER_IP = "localhost";
    private static final int SERVER_PORT = 1234;
    private ObjectInputStream in;
    private ObjectOutputStream out;
    private Socket socket;
    private ImageIcon icon;

    public Login() {
        try {
            FlatLightLaf.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        conneted();
    }

    private void initRegister() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        SlidePanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserNameRegister = new javax.swing.JTextField();
        txtPassRegister = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        LoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserNameLogin = new javax.swing.JTextField();
        txtPassLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        MainPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(800, 500));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SlidePanel.setBackground(new java.awt.Color(62, 39, 35));
        SlidePanel.setPreferredSize(new java.awt.Dimension(400, 500));
        SlidePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                SlidePanelComponentHidden(evt);
            }
        });
        SlidePanel.setLayout(new java.awt.GridBagLayout());

        Logo.setFont(new java.awt.Font("SansSerif", 0, 80)); // NOI18N
        Logo.setForeground(new java.awt.Color(221, 194, 170));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("☕");
        Logo.setMinimumSize(new java.awt.Dimension(100, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        SlidePanel.add(Logo, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 220, 190));
        jLabel9.setText("Coffee Manager");
        jLabel9.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        SlidePanel.add(jLabel9, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 220, 190));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Welcome!");
        jLabel7.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        SlidePanel.add(jLabel7, gridBagConstraints);

        jLayeredPane1.setLayer(SlidePanel, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(SlidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        RegisterPanel.setBackground(new java.awt.Color(245, 235, 230));
        RegisterPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        RegisterPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 39, 35));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Account");
        jLabel3.setToolTipText("");
        jLabel3.setMinimumSize(new java.awt.Dimension(280, 35));
        jLabel3.setPreferredSize(new java.awt.Dimension(280, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        RegisterPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 50, 40));
        jLabel4.setText("Please create your new account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 35, 0);
        RegisterPanel.add(jLabel4, gridBagConstraints);

        txtUserNameRegister.setToolTipText("");
        txtUserNameRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNameRegister.setMinimumSize(new java.awt.Dimension(280, 35));
        txtUserNameRegister.setPreferredSize(new java.awt.Dimension(280, 35));
        txtUserNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        RegisterPanel.add(txtUserNameRegister, gridBagConstraints);

        txtPassRegister.setPreferredSize(new java.awt.Dimension(280, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        RegisterPanel.add(txtPassRegister, gridBagConstraints);
        txtPassLogin.setText("");
        txtPassLogin.putClientProperty("JPasswordField.placeholderText", "Password");
        txtPassLogin.putClientProperty("JPasswordField.showRevealButton", true);

        btnSignup.setBackground(new java.awt.Color(93, 64, 55));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(240, 220, 190));
        btnSignup.setText("Sign Up");
        btnSignup.setBorder(new com.formdev.flatlaf.ui.FlatButtonBorder());
        btnSignup.setPreferredSize(new java.awt.Dimension(180, 35));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        RegisterPanel.add(btnSignup, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(70, 50, 40));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Already have an account ?");
        jLabel11.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        RegisterPanel.add(jLabel11, gridBagConstraints);

        btnSignIn.setBackground(new java.awt.Color(93, 64, 55));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(240, 220, 190));
        btnSignIn.setText("Sign in");
        btnSignIn.setToolTipText("");
        btnSignIn.setBorder(new com.formdev.flatlaf.ui.FlatButtonBorder());
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        RegisterPanel.add(btnSignIn, new java.awt.GridBagConstraints());

        jLayeredPane1.add(RegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));
        txtUserNameRegister.putClientProperty("JTextField.placeholderText", "Username");
        txtPassRegister.putClientProperty("JTextField.placeholderText", "Password");

        LoginPanel.setBackground(new java.awt.Color(245, 235, 230));
        LoginPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 50, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");
        jLabel1.setToolTipText("");
        jLabel1.setMinimumSize(new java.awt.Dimension(280, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(280, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        LoginPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 50, 40));
        jLabel2.setText("Please log in to your account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 25, 0);
        LoginPanel.add(jLabel2, gridBagConstraints);

        txtUserNameLogin.setToolTipText("");
        txtUserNameLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNameLogin.setMinimumSize(new java.awt.Dimension(280, 35));
        txtUserNameLogin.setPreferredSize(new java.awt.Dimension(280, 35));
        txtUserNameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        LoginPanel.add(txtUserNameLogin, gridBagConstraints);

        txtPassLogin.setPreferredSize(new java.awt.Dimension(280, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        LoginPanel.add(txtPassLogin, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(93, 64, 55));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(240, 220, 190));
        btnLogin.setText("Login");
        btnLogin.setBorder(new com.formdev.flatlaf.ui.FlatButtonBorder());
        btnLogin.setPreferredSize(new java.awt.Dimension(180, 35));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        LoginPanel.add(btnLogin, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(70, 50, 40));
        jLabel10.setText("New to the crew?");
        jLabel10.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        LoginPanel.add(jLabel10, gridBagConstraints);

        btnCreateAccount.setBackground(new java.awt.Color(93, 64, 55));
        btnCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(240, 220, 190));
        btnCreateAccount.setText("Create an account");
        btnCreateAccount.setToolTipText("");
        btnCreateAccount.setBorder(new com.formdev.flatlaf.ui.FlatButtonBorder());
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        LoginPanel.add(btnCreateAccount, new java.awt.GridBagConstraints());

        jLayeredPane1.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));
        txtUserNameLogin.putClientProperty("JTextField.placeholderText", "Username");
        txtPassLogin.putClientProperty("JTextField.placeholderText", "Password");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(814, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameLoginActionPerformed


    }//GEN-LAST:event_txtUserNameLoginActionPerformed

    private void txtUserNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameRegisterActionPerformed

    private void SlidePanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SlidePanelComponentHidden

    }//GEN-LAST:event_SlidePanelComponentHidden

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        int currentX = SlidePanel.getX();
        int targetX = 400;
        int speed = 20;

        javax.swing.Timer timer = new javax.swing.Timer(10, new java.awt.event.ActionListener() {
            int x = SlidePanel.getX();
            int targetX = 400;
            int speed = 20;

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (x < targetX) {
                    x += speed;
                    SlidePanel.setLocation(x, SlidePanel.getY());
                    Login.this.repaint();

                } else {
                    SlidePanel.setLocation(targetX, SlidePanel.getY());
                    Login.this.repaint();
                    ((javax.swing.Timer) e.getSource()).stop();
                }
            }
        });

        timer.start();

    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        int currentX = SlidePanel.getX();
        int targetX = 400;
        int speed = 20;

        javax.swing.Timer timer = new javax.swing.Timer(10, new java.awt.event.ActionListener() {
            int x = SlidePanel.getX();
            int targetX = 0;
            int speed = 20;

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (x > targetX) {
                    x -= speed;
                    SlidePanel.setLocation(x, SlidePanel.getY());
                    Login.this.repaint();

                } else {
                    SlidePanel.setLocation(targetX, SlidePanel.getY());
                    Login.this.repaint();
                    ((javax.swing.Timer) e.getSource()).stop();
                }
            }
        });

        timer.start();
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                try{    
            String username = txtUserNameLogin.getText();
            String password =String.valueOf(txtPassLogin.getPassword());
            //tạo user
            Account acc = new Account();
            acc.setUsername(username);
            acc.setPassword(password);
            //tạo request
            Request req = new Request("LOGIN", acc);
            //gửi request
            out.writeObject(req);
            out.flush(); 
            //nhận response
            Response res =(Response)in.readObject();
            JOptionPane.showMessageDialog(this,res.getMessage());
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        try {
            String username = txtUserNameRegister.getText();
            String password = String.valueOf(txtPassRegister.getPassword());

            Account acc = new Account();
            acc.setUsername(username);
            acc.setPassword(password);

            Request req = new Request("REGISTER", acc);
            out.writeObject(req);
            out.flush();

            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID phải là số!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();
        UIManager.put("Component.arc", 10);
        UIManager.put("Button.arc", 99);
        UIManager.put("TextComponent.arc", 10);
        UIManager.put("Button.borderColor", new Color(240, 220, 190));
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    public void conneted() {
        try {
            socket = new Socket(SERVER_IP, SERVER_PORT);
            out = new ObjectOutputStream(socket.getOutputStream());//phải tạo output trước không sẽ bị deadlock
            out.flush();
            in = new ObjectInputStream(socket.getInputStream());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JPanel SlidePanel;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField txtPassLogin;
    private javax.swing.JPasswordField txtPassRegister;
    private javax.swing.JTextField txtUserNameLogin;
    private javax.swing.JTextField txtUserNameRegister;
    // End of variables declaration//GEN-END:variables
}
