/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.ManagerGUI;

import Client.ClientConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.*;
import shared.RequestResponse.*;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author admin
 */
public class AccountGui extends javax.swing.JPanel {

    private List<Account> allAccounts = new java.util.ArrayList<>();

    /**
     * Creates new form AccountGui
     */
    public AccountGui() {
        initComponents();

        // Key đúng để hiển thị icon kính lúp bên trái
        txtFind.putClientProperty("JTextField.leadingIcon", new com.formdev.flatlaf.icons.FlatSearchIcon());
        // Placeholder text
        txtFind.putClientProperty("JTextField.placeholderText", "Tìm kiếm nhân viên...");

        setupTableStyle();
        try {
            load();
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        HeadPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelToolBar = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 246, 240));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        HeadPanel.setBackground(new java.awt.Color(245, 235, 230));
        HeadPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        HeadPanel.setMinimumSize(new java.awt.Dimension(261, 40));
        HeadPanel.setPreferredSize(new java.awt.Dimension(285, 80));
        HeadPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 39, 35));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (7).png"))); // NOI18N
        jLabel1.setText("Quản lý tài khoản");
        jLabel1.setIconTextGap(12);
        HeadPanel.add(jLabel1, java.awt.BorderLayout.WEST);

        add(HeadPanel, java.awt.BorderLayout.NORTH);

        panelCard.setBackground(new java.awt.Color(245, 235, 230));
        panelCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)), javax.swing.BorderFactory.createEmptyBorder(20, 40, 40, 40)));
        panelCard.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(250, 246, 240));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 154, 43), 2, true));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Display Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(245, 240, 235));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(225, 215, 210));
        jTable1.setSelectionForeground(new java.awt.Color(74, 46, 43));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jTable1.getTableHeader().setBackground(new java.awt.Color(240, 235, 230)); // Màu xám kem nền
        jTable1.getTableHeader().setForeground(new java.awt.Color(62, 39, 35));

        panelCard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelToolBar.setBackground(new java.awt.Color(255, 255, 255));
        panelToolBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        panelToolBar.setOpaque(false);
        panelToolBar.setPreferredSize(new java.awt.Dimension(900, 80));

        txtFind.setColumns(25);
        txtFind.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFind.setToolTipText("");
        txtFind.setPreferredSize(new java.awt.Dimension(450, 42));
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        panelToolBar.add(txtFind);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Staff" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(140, 35));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panelToolBar.add(jComboBox1);

        jButton1.setBackground(new java.awt.Color(92, 82, 49));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelToolBar.add(jButton1);

        jButton2.setBackground(new java.awt.Color(230, 220, 200));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(80, 60, 40));
        jButton2.setText("Reset");
        jButton2.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelToolBar.add(jButton2);

        panelCard.add(panelToolBar, java.awt.BorderLayout.NORTH);

        add(panelCard, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(245, 235, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 15, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        btnThem.setBackground(new java.awt.Color(92, 82, 49));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (5).png"))); // NOI18N
        btnThem.setText("Thêm tài khoản");
        btnThem.setIconTextGap(8);
        btnThem.setPreferredSize(new java.awt.Dimension(200, 45));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);

        btnSua.setBackground(new java.awt.Color(242, 235, 235));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/write.png"))); // NOI18N
        btnSua.setText("Sửa tài khoản");
        btnSua.setIconTextGap(8);
        btnSua.setPreferredSize(new java.awt.Dimension(200, 45));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(139, 26, 26));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (6).png"))); // NOI18N
        btnXoa.setText("Xóa tài khoản");
        btnXoa.setIconTextGap(8);
        btnXoa.setPreferredSize(new java.awt.Dimension(200, 45));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    //thêm tài khoản
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String username = JOptionPane.showInputDialog(this, "Nhập username:");
        if (username == null) {
            return;
        }

        String password = JOptionPane.showInputDialog(this, "Nhập password:");
        if (password == null) {
            return;
        }

        String displayname = JOptionPane.showInputDialog(this, "Nhập tên hiển thị:");
        if (displayname == null) {
            return;
        }

        String[] options = {"0 - Staff", "1 - Manager"};
        String choice = (String) JOptionPane.showInputDialog(this, "Chọn loại tài khoản:", "Type",
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == null) {
            return;
        }
        int type = choice.startsWith("0") ? 0 : 1;

        Account ac = new Account(displayname, username, password, type);

        try {
            Request req = new Request("ADD ACCOUNT", ac);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            if (res.getStatus().equals("SUCCESS")) {
                load();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed
    //sửa tài khoản (type)
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản trong bảng!");
            return;
        }

        int id = (int) jTable1.getValueAt(row, 0);
        String[] options = {"0 - Staff", "1 - Manager"};
        String choice = (String) JOptionPane.showInputDialog(this, "Chọn loại tài khoản mới:", "Sửa Type",
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice != null) {
            Account ac = new Account();
            ac.setId(id);
            ac.setType(choice.startsWith("0") ? 0 : 1);

            try {
                Request req = new Request("UPDATE ACCOUNT", ac);
                ClientConnection.getOut().writeObject(req);
                ClientConnection.getOut().flush();
                Response res = (Response) ClientConnection.getIn().readObject();
                JOptionPane.showMessageDialog(this, res.getMessage());
                if (res.getStatus().equals("SUCCESS")) {
                    load();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed
    //xóa tài khoản
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tài khoản ID: " + jTable1.getValueAt(row, 0) + "?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            int id = (int) jTable1.getValueAt(row, 0);
            Account ac = new Account();
            ac.setId(id);

            try {
                Request req = new Request("DELETE ACCOUNT", ac);
                ClientConnection.getOut().writeObject(req);
                ClientConnection.getOut().flush();
                Response res = (Response) ClientConnection.getIn().readObject();
                JOptionPane.showMessageDialog(this, res.getMessage());
                if (res.getStatus().equals("SUCCESS")) {
                    load();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed

    }//GEN-LAST:event_txtFindActionPerformed

    //tìm kiếm theo username
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String keyword = txtFind.getText().trim().toLowerCase();

        List<Account> filtered = new java.util.ArrayList<>();

        for (Account ac : allAccounts) {
            if (ac.getUsername().toLowerCase().contains(keyword)
                    || ac.getDisplayName().toLowerCase().contains(keyword)) {
                filtered.add(ac);
            }
        }

        renderTable(filtered);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        renderTable(allAccounts);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selected = (String) jComboBox1.getSelectedItem();

        List<Account> filtered = new java.util.ArrayList<>();

        for (Account ac : allAccounts) {
            String role = (ac.getType() == 0) ? "Staff" : "Manager";

            if (selected.equals(role)) {
                filtered.add(ac);
            }
        }

        renderTable(filtered);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void load() {
        try {
            Request req = new Request("GET ACCOUNTS", null);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();

            if (res.getStatus().equals("SUCCESS")) {

                allAccounts = (List<Account>) res.getData(); // LƯU LẠI

                renderTable(allAccounts);

            } else {
                JOptionPane.showMessageDialog(this, "Lỗi: " + res.getMessage());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void renderTable(List<Account> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Account ac : list) {
            String role = ac.getType() == 0 ? "Staff" : "Manager";

            model.addRow(new Object[]{
                ac.getId(),
                ac.getUsername(),
                ac.getDisplayName(),
                role
            });
        }
    }
    
        private void setupTableStyle() {
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 15));
        header.setPreferredSize(new Dimension(100, 46));
        header.setBackground(new Color(78, 46, 42));
        header.setForeground(Color.WHITE);
        
        jTable1.setRowHeight(48);
        
        DefaultTableCellRenderer center
                = new DefaultTableCellRenderer();

        center.setHorizontalAlignment(
                SwingConstants.CENTER);

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(center);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelToolBar;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
