/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.ManagerGUI;

import Client.ClientConnection;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.Bill;
import shared.RequestResponse.*;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.plot.CategoryPlot;
import javax.swing.JFrame;
import shared.Model.BillInfor;

/**
 *
 * @author admin
 */
public class BillManagerGUI extends javax.swing.JPanel {

    private List<Bill> bills;
    private List<BillInfor> billInfors;
    private com.toedter.calendar.JDateChooser dateChooser;

    /**
     * Creates new form BillManagerGUI
     */
    public BillManagerGUI() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 235, 230));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 10, 25));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 46, 43));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/invoice.png"))); // NOI18N
        jLabel3.setText("Quản lý hóa đơn");
        jLabel3.setIconTextGap(10);
        jPanel1.add(jLabel3, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Check in", "Check out", "Giảm giá(%)", "Giá tiền (VNĐ)", "Trạng thái", "Bàn đặt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25), new javax.swing.border.LineBorder(new java.awt.Color(245, 235, 230), 6, true)));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Doanh thu hiện tại:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("VNĐ");

        jButton1.setBackground(new java.awt.Color(245, 235, 230));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/coins (1).png"))); // NOI18N

        jButton2.setText("thống kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lọc hóa đơn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("hiển thị tất cả");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("sản phẩm bán chạy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showRevenueChart();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dateChooser = new com.toedter.calendar.JDateChooser();
        dateChooser.setDateFormatString("dd/MM/yyyy");

        int result = JOptionPane.showConfirmDialog(
                this,
                dateChooser,
                "Chọn ngày",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            java.util.Date selectedDate = dateChooser.getDate();

            if (selectedDate != null) {
                filterByDate(selectedDate);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadBill(bills);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Request req = new Request("GET FOOD FREQ", null);
            Response res = (Response) ClientConnection.sendRequest(req);

            if (res == null || !"SUCCESS".equals(res.getStatus())) {
                JOptionPane.showMessageDialog(this, "Không lấy được dữ liệu");
                return;
            }

            List<BillInfor> list = (List<BillInfor>) res.getData();

            Map<String, Integer> map = new HashMap<>();

            for (BillInfor b : list) {
                map.put(
                        b.getFoodName(),
                        map.getOrDefault(b.getFoodName(), 0) + b.getQuantity()
                );
            }

            showFoodBarChart(map);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private void showRevenueChart() {
        if (bills == null || bills.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không có dữ liệu");
            return;
        }
        Map<String, BigDecimal> revenueByDate = new TreeMap<>();

        SimpleDateFormat sdf
                = new SimpleDateFormat("dd/MM/yyyy");

        for (Bill bill : bills) {

            if (bill.getStatus() != Bill.PAID
                    || bill.getDateCheckOut() == null) {
                continue;
            }
            String date = sdf.format(bill.getDateCheckOut());
            revenueByDate.put(
                    date,
                    revenueByDate.getOrDefault(
                            date,
                            BigDecimal.ZERO)
                            .add(bill.getTotalPrice())
            );
        }
        DefaultCategoryDataset dataset
                = new DefaultCategoryDataset();
        for (Map.Entry<String, BigDecimal> entry
                : revenueByDate.entrySet()) {
            dataset.addValue(
                    entry.getValue(),
                    "Doanh thu",
                    entry.getKey()
            );
        }
        JFreeChart chart
                = ChartFactory.createLineChart(
                        "Doanh thu theo ngày",
                        "Ngày",
                        "VNĐ",
                        dataset
                );
        ChartPanel panel
                = new ChartPanel(chart);
        JFrame frame
                = new JFrame("Biểu đồ doanh thu");
        frame.setDefaultCloseOperation(
                JFrame.DISPOSE_ON_CLOSE);
        frame.add(panel);
        frame.setSize(900, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        CategoryPlot plot = chart.getCategoryPlot();

        LineAndShapeRenderer renderer
                = (LineAndShapeRenderer) plot.getRenderer();

        renderer.setDefaultShapesVisible(true);
        renderer.setDefaultShapesFilled(true);

        renderer.setDefaultItemLabelsVisible(true);
        renderer.setDefaultItemLabelGenerator(
                new StandardCategoryItemLabelGenerator());
    }

    private void showFoodBarChart(Map<String, Integer> data) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Map.Entry<String, Integer> e : data.entrySet()) {
            dataset.addValue(e.getValue(), "Số lượng bán", e.getKey());
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Top sản phẩm bán chạy",
                "Món ăn",
                "Số lượng",
                dataset
        );

        ChartPanel panel = new ChartPanel(barChart);

        JFrame frame = new JFrame("Thống kê sản phẩm bán chạy");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(panel);
        frame.setSize(900, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void loadData() {
        try {
            Request req = new Request("GET ALL BILLS", null);
            Response res = (Response) ClientConnection.sendRequest(req);
            if (res != null && "SUCCESS".equals(res.getStatus())) {
                bills = (List<Bill>) res.getData();
                loadBill(bills);
            } else {
                JOptionPane.showMessageDialog(this, "Không tải được danh sách hóa đơn");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối server");
        }
    }

    public void loadBill(List<Bill> bills) {

        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        BigDecimal revenue = BigDecimal.ZERO;

        for (Bill bill : bills) {

            model.addRow(new Object[]{
                bill.getId(),
                bill.getDateCheckIn(),
                bill.getDateCheckOut(),
                bill.getDiscount(),
                bill.getTotalPrice(),
                bill.getStatus() == 0
                ? "Chưa thanh toán"
                : "Đã thanh toán",
                bill.getTableID()
            });

            if (bill.getStatus() == 1) {
                revenue = revenue.add(bill.getTotalPrice());
            }
        }

        jLabel2.setText(revenue.toString() + " VNĐ");
    }

    private void filterByDate(java.util.Date selectedDate) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String target = sdf.format(selectedDate);

        List<Bill> filtered = new java.util.ArrayList<>();

        for (Bill b : bills) {
            if (b.getDateCheckOut() == null) {
                continue;
            }

            if (target.equals(sdf.format(b.getDateCheckOut()))) {
                filtered.add(b);
            }
        }

        loadBill(filtered);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
