package Client.ManagerGUI;

import Client.ClientConnection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import shared.Model.CategoryFood;
import shared.Model.Food;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author ADMIN
 */

public class InventoryGui extends javax.swing.JPanel {

    /**
     * Creates new form InventoryGui
     */
    private int currentCategoryId = -1;

    public InventoryGui() {

        initComponents();

        displayCategory();

// Tăng độ cao mỗi thẻ danh mục lên 55px cho cao ráo chuẩn POS
        jList1.setFixedCellHeight(55);


        jList1.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                    JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                // 1. TỰ ĐỘNG CÀI ICON CHIẾC CỐC CỦA FLATLAF (Không lo lỗi font, tự đổi màu trắng khi click!)
                // Sử dụng icon khay Tree của FlatLaf làm biểu tượng Vector sắc nét
                label.setIcon(javax.swing.UIManager.getIcon("Tree.leafIcon")); 
                label.setIconTextGap(12); // Khoảng cách giữa icon và chữ

                // 2. TẠO BORDER KHE HỞ THỰC TẾ: Đẩy các ô cách nhau 8px đứng, đệm lề trong thoáng đãng
                label.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createEmptyBorder(0, 0, 8, 0),       // Khe rãnh hở giữa các thẻ đứng
                        BorderFactory.createEmptyBorder(10, 15, 10, 15)    // Khoảng đệm chữ và rìa trong của thẻ
                ));

                return label;
            }
        });

        setupTableStyle();


        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selectedValue = jList1.getSelectedValue();
                if (selectedValue != null) {
                    try {
                        // Bóc tách trích xuất lấy con số ID nằm trong dấu ngoặc vuông "[ID]"
                        int openBracket = selectedValue.indexOf("[");
                        int closeBracket = selectedValue.indexOf("]");
                        if (openBracket != -1 && closeBracket != -1) {
                            String idStr = selectedValue.substring(openBracket + 1, closeBracket);
                            currentCategoryId = Integer.parseInt(idStr); // Cập nhật mã danh mục hiện tại công khai

                            // Tải danh sách món ăn từ Server đổ về bảng theo mã loại vừa bóc
                            displayFood(currentCategoryId);

                            // Xóa ảnh cũ ở khung lề phải khi đổi danh mục
                            jLabel4.setIcon(null);
                            jLabel4.setText("      Không có ảnh");
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showFoodImage();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnThemLoai = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 11), new java.awt.Dimension(0, 11), new java.awt.Dimension(32767, 11));
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnXoaLoai = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        panelToolBar = new javax.swing.JPanel();
        btnThemMon = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThemAnh = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        btnXoaAnh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 35), new java.awt.Dimension(0, 35), new java.awt.Dimension(32767, 35));

        setBackground(new java.awt.Color(245, 235, 230));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 30, 25), new javax.swing.border.LineBorder(new java.awt.Color(245, 235, 230), 1, true)));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        HeadPanel.setBackground(new java.awt.Color(245, 235, 230));
        HeadPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        HeadPanel.setOpaque(false);
        HeadPanel.setLayout(new javax.swing.BoxLayout(HeadPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 39, 35));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu (8).png"))); // NOI18N
        jLabel3.setText("Quản lý kho hàng");
        jLabel3.setIconTextGap(12);
        HeadPanel.add(jLabel3);

        add(HeadPanel, java.awt.BorderLayout.NORTH);

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        LeftPanel.setMinimumSize(new java.awt.Dimension(210, 600));
        LeftPanel.setPreferredSize(new java.awt.Dimension(210, 600));
        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 39, 35));
        jLabel2.setText("Danh mục món");
        LeftPanel.add(jLabel2);
        LeftPanel.add(filler2);

        btnThemLoai.setBackground(new java.awt.Color(92, 82, 49));
        btnThemLoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus (4).png"))); // NOI18N
        btnThemLoai.setText(" Thêm loại");
        btnThemLoai.setAlignmentY(1.0F);
        btnThemLoai.setBorderPainted(false);
        btnThemLoai.setIconTextGap(8);
        btnThemLoai.setMaximumSize(new java.awt.Dimension(155, 31));
        btnThemLoai.setMinimumSize(new java.awt.Dimension(155, 31));
        btnThemLoai.setPreferredSize(new java.awt.Dimension(160, 40));
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });
        LeftPanel.add(btnThemLoai);
        LeftPanel.add(filler1);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 235, 230), 1, true));

        jList1.setBorder(null);
        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setFixedCellHeight(42);
        jList1.setMinimumSize(new java.awt.Dimension(69, 42));
        jList1.setPreferredSize(new java.awt.Dimension(69, 42));
        jList1.setSelectedIndex(0);
        jList1.setSelectionBackground(new java.awt.Color(253, 245, 237));
        jList1.setSelectionForeground(new java.awt.Color(62, 39, 35));
        jScrollPane2.setViewportView(jList1);

        LeftPanel.add(jScrollPane2);
        LeftPanel.add(filler3);

        btnXoaLoai.setBackground(new java.awt.Color(139, 26, 26));
        btnXoaLoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minus.png"))); // NOI18N
        btnXoaLoai.setText("Xóa loại");
        btnXoaLoai.setAlignmentY(1.0F);
        btnXoaLoai.setBorderPainted(false);
        btnXoaLoai.setIconTextGap(8);
        btnXoaLoai.setMaximumSize(new java.awt.Dimension(170, 31));
        btnXoaLoai.setPreferredSize(new java.awt.Dimension(170, 40));
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });
        LeftPanel.add(btnXoaLoai);

        add(LeftPanel, java.awt.BorderLayout.WEST);
        btnThemLoai.putClientProperty("JButton.buttonType", "roundRect");

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 10, 12, 12));
        RightPanel.setMinimumSize(new java.awt.Dimension(590, 600));
        RightPanel.setPreferredSize(new java.awt.Dimension(590, 600));
        RightPanel.setLayout(new java.awt.BorderLayout());

        panelToolBar.setBackground(new java.awt.Color(245, 235, 230));
        panelToolBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 0));
        panelToolBar.setOpaque(false);
        panelToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        btnThemMon.setBackground(new java.awt.Color(92, 82, 49));
        btnThemMon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemMon.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus (4).png"))); // NOI18N
        btnThemMon.setText(" Thêm món");
        btnThemMon.setBorderPainted(false);
        btnThemMon.setIconTextGap(8);
        btnThemMon.setPreferredSize(new java.awt.Dimension(170, 40));
        btnThemMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonActionPerformed(evt);
            }
        });
        panelToolBar.add(btnThemMon);

        btnSua.setBackground(new java.awt.Color(242, 235, 235));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(69, 39, 35));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/editing (2).png"))); // NOI18N
        btnSua.setText("Sửa món");
        btnSua.setIconTextGap(8);
        btnSua.setPreferredSize(new java.awt.Dimension(170, 40));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        panelToolBar.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(139, 26, 26));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        btnXoa.setText("Xóa món");
        btnXoa.setIconTextGap(8);
        btnXoa.setPreferredSize(new java.awt.Dimension(170, 40));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        panelToolBar.add(btnXoa);

        RightPanel.add(panelToolBar, java.awt.BorderLayout.PAGE_START);
        jTable1.getTableHeader().setBackground(new java.awt.Color(248, 245, 242));
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
        jTable1.getTableHeader().setForeground(new java.awt.Color(62, 39, 35));
        jTable1.getTableHeader().setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 225, 220)));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 154, 43), 2));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên món ăn", "Giá nhập", "Giá bán"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(248, 245, 240));
        jTable1.setRowHeight(42);
        jTable1.setSelectionBackground(new java.awt.Color(225, 215, 210));
        jTable1.setSelectionForeground(new java.awt.Color(74, 46, 43));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        RightPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(RightPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(253, 245, 237));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 180));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        btnThemAnh.setBackground(new java.awt.Color(30, 58, 138));
        btnThemAnh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/download (2).png"))); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.setIconTextGap(8);
        btnThemAnh.setMaximumSize(new java.awt.Dimension(9999, 9999));
        btnThemAnh.setMinimumSize(new java.awt.Dimension(0, 0));
        btnThemAnh.setPreferredSize(new java.awt.Dimension(170, 40));
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });
        jPanel4.add(btnThemAnh);
        jPanel4.add(filler4);

        btnXoaAnh.setBackground(new java.awt.Color(139, 26, 26));
        btnXoaAnh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        btnXoaAnh.setText("Xóa ảnh");
        btnXoaAnh.setIconTextGap(8);
        btnXoaAnh.setMaximumSize(new java.awt.Dimension(9999, 9999));
        btnXoaAnh.setMinimumSize(new java.awt.Dimension(0, 0));
        btnXoaAnh.setPreferredSize(new java.awt.Dimension(170, 40));
        btnXoaAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAnhActionPerformed(evt);
            }
        });
        jPanel4.add(btnXoaAnh);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 39, 35));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/image.png"))); // NOI18N
        jLabel1.setText("Ảnh món");
        jLabel1.setIconTextGap(12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(253, 245, 237));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 410));

        jLabel4.setBackground(new java.awt.Color(253, 245, 237));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("                                      Không có ảnh");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 20, 1));
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category trước!");
            return;
        }
        try {
            String name = JOptionPane.showInputDialog(this, "Nhập tên món ăn:");
            if (name == null || name.trim().isEmpty()) {
                return;
            }

            String priceinStr = JOptionPane.showInputDialog(this, "Giá nhập:");
            if (priceinStr == null || priceinStr.trim().isEmpty()) {
                return;
            }

            String priceoutStr = JOptionPane.showInputDialog(this, "Giá bán:");
            if (priceoutStr == null || priceoutStr.trim().isEmpty()) {
                return;
            }

            BigDecimal pricein = new BigDecimal(priceinStr.trim());
            BigDecimal priceout = new BigDecimal(priceoutStr.trim());

            Food food = new Food();
            food.setNameFood(name.trim());
            food.setPriceIn(pricein);
            food.setPriceOut(priceout);
            food.setIdcategory(currentCategoryId);

            Request req = new Request("INSERT FOOD", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();

            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sai định dạng tiền tệ!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemMonActionPerformed

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        String name = JOptionPane.showInputDialog(this, "Nhập tên loại mới:");
        if (name == null || name.trim().isEmpty()) {
            return;
        }

        try {
            CategoryFood c = new CategoryFood();
            c.setTen(name.trim());

            Request req = new Request("INSERT CATEGORY", c);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();

            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());

            if ("SUCCESS".equals(res.getStatus())) {
                displayCategory();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn cần sửa thông tin trên bảng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int foodId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String oldName = jTable1.getValueAt(row, 1).toString();

        String newName = JOptionPane.showInputDialog(this, "Cập nhật tên món ăn:", oldName);
        if (newName == null || newName.trim().isEmpty()) {
            return;
        }

        String newPriceOut = JOptionPane.showInputDialog(this, "Cập nhật giá bán mới:");
        if (newPriceOut == null || newPriceOut.trim().isEmpty()) {
            return;
        }

        try {
            Food food = new Food();
            food.setId(foodId);
            food.setNameFood(newName.trim());
            food.setPriceOut(new BigDecimal(newPriceOut.trim()));

            Request req = new Request("UPDATE FOOD", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();

            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId); // Tải lại dữ liệu bảng
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần xóa");
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE FOOD", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId);
                jTable1.clearSelection();
                jLabel4.setIcon(null);
                jLabel4.setText("không có ảnh");
            }
            JOptionPane.showMessageDialog(this, res.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại danh mục cần xóa ở khay bên trái!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Xóa danh mục sẽ xóa toàn bộ món ăn bên trong! Bạn vẫn muốn tiếp tục?", "Cảnh báo xóa loại", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // ĐÓNG GÓI ĐÚNG ĐỐI TƯỢNG CategoryFood để Server ép kiểu không bị nổ ClassCastException
                CategoryFood c = new CategoryFood();
                c.setId(currentCategoryId);

                Request req = new Request("DELETE CATEGORY", c);
                ClientConnection.getOut().writeObject(req);
                ClientConnection.getOut().flush();

                Response res = (Response) ClientConnection.getIn().readObject();
                JOptionPane.showMessageDialog(this, res.getMessage());
                
                if ("SUCCESS".equals(res.getStatus())) {
                    currentCategoryId = -1; // Reset mã ID chọn
                    
                    // Clear trắng dòng trên bảng tránh rác dữ liệu cũ
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setRowCount(0);
                    
                    // Reset khay ảnh lề phải
                    jLabel4.setIcon(null);
                    jLabel4.setText("      Không có ảnh");
                    
                    // Cách ly luồng nạp lại danh mục ra một tiến trình Swing phụ để chặn đứng vĩnh viễn EOFException!
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        displayCategory();
                    });
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnXoaAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAnhActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category");
            return;
        }
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần xóa ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE IMAGE", food);
            // gửi server
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            if (res.getStatus().equals("SUCCESS")) {
                JOptionPane.showMessageDialog(this, "xóa ảnh thành công");
                showFoodImage();
            } else {
                JOptionPane.showMessageDialog(this, "xóa ảnh thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
    }//GEN-LAST:event_btnXoaAnhActionPerformed
    }
    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category");
            return;
        }
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần thêm ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            // file chooser
            JFileChooser jf = new JFileChooser();
            jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
            // filter ảnh
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg");
            jf.setFileFilter(filter);
            // mở dialog
            int result = jf.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = jf.getSelectedFile();
                // đọc file thành byte[]
                byte[] imageData = Files.readAllBytes(file.toPath());
                // tạo object food
                Food food = new Food();
                food.setId(foodId);
                food.setImageData(imageData);
                // gửi tên file
                food.setImagePath(file.getName());
                // request
                Request req = new Request("UPLOAD IMAGE", food);
                // gửi server
                ClientConnection.getOut().writeObject(req);
                ClientConnection.getOut().flush();
                Response res = (Response) ClientConnection.getIn().readObject();
                if (res.getStatus().equals("SUCCESS")) {
                    JOptionPane.showMessageDialog(this, "Upload ảnh thành công");
                    showFoodImage();
                } else {
                    JOptionPane.showMessageDialog(this, "Upload ảnh thất bại");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemAnhActionPerformed

    public void showFoodImage() {
    int row = jTable1.getSelectedRow();
    if (row == -1) {
        jLabel4.setIcon(null);
        jLabel4.setText("      Không có ảnh");
        return;
    }
    Object cellValue = jTable1.getValueAt(row, 0);
    if (cellValue == null) {
        jLabel4.setIcon(null);
        jLabel4.setText("      Không có ảnh");
        return;
    }

    try {
        int foodId = Integer.parseInt(cellValue.toString());
        Request req = new Request("SHOW IMAGE", foodId);
        ClientConnection.getOut().writeObject(req);
        ClientConnection.getOut().flush();

        Response res = (Response) ClientConnection.getIn().readObject();
        if (res != null && "SUCCESS".equals(res.getStatus())) {
            Food food = (Food) res.getData();
            byte[] imageBytes = food.getImageData();

            if (imageBytes != null && imageBytes.length > 0) {
                ImageIcon icon = new ImageIcon(imageBytes);
                Image img = icon.getImage();
                Image scaled = img.getScaledInstance(jLabel4.getWidth() - 20, jLabel4.getHeight() - 20, Image.SCALE_SMOOTH);
                jLabel4.setIcon(new ImageIcon(scaled));
                jLabel4.setText("");
            } else {
                jLabel4.setIcon(null);
                jLabel4.setText("      Không có ảnh");
            }
        } else {
            jLabel4.setIcon(null);
            jLabel4.setText("      Không có ảnh");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public void displayFood(int categoryId) {
    try {
        Request req = new Request("SELECT FOOD BY CATEGORY", categoryId);
        ClientConnection.getOut().writeObject(req);
        ClientConnection.getOut().flush();
        Response res = (Response) ClientConnection.getIn().readObject();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        if ("SUCCESS".equals(res.getStatus())) {
            DecimalFormat df = new DecimalFormat("###,###");
            ArrayList<Food> list = (ArrayList<Food>) res.getData();
            for (Food f : list) {
                String priceInFormatted = (f.getPriceIn() != null) ? df.format(f.getPriceIn()) : "0";
                String priceOutFormatted = (f.getPriceOut() != null) ? df.format(f.getPriceOut()) : "0";
                model.addRow(new Object[]{
                    f.getId(),
                    f.getNameFood(),
                    priceInFormatted,
                    priceOutFormatted});
            }
        } else {
            JOptionPane.showMessageDialog(this, res.getMessage());
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

public void displayCategory() {
        try {
            Request req = new Request("SELECT CATEGORY", null);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();

            Response res = (Response) ClientConnection.getIn().readObject();

            if ("SUCCESS".equals(res.getStatus())) {
                ArrayList<CategoryFood> list = (ArrayList<CategoryFood>) res.getData();
                DefaultListModel<String> listModel = new DefaultListModel<>();

                for (CategoryFood c : list) {
                    // 🌟 ĐÃ FIX: Dọn sạch khoảng trắng rác, chỉ để chữ thuần túy để Renderer tự chèn Icon FlatLaf tự động!
                    listModel.addElement("[" + c.getId() + "] - " + c.getTen());
                }
                jList1.setModel(listModel);

                if (!list.isEmpty()) {
                    jList1.setSelectedIndex(0); // Tự động chọn danh mục đầu tiên khi tải xong
                }
            } else if ("NO CATEGORY".equals(res.getStatus())) {
                JOptionPane.showMessageDialog(this, "Hệ thống chưa dữ liệu loại danh mục nào!");
            } else {
                JOptionPane.showMessageDialog(this, res.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        private void setupTableStyle() {
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 15));
        header.setPreferredSize(new Dimension(100, 46));
        header.setBackground(new Color(78, 46, 42));
        header.setForeground(Color.WHITE);
        
        jTable1.setRowHeight(48);
        
        DefaultTableCellRenderer center
                = new DefaultTableCellRenderer();

        center.setHorizontalAlignment(
                SwingConstants.CENTER);

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(center);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnThemMon;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaAnh;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelToolBar;
    // End of variables declaration//GEN-END:variables
}
