/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.ManagerGUI;
import Client.ClientConnection;
import java.text.DecimalFormat;
import java.awt.Image;
import java.io.File;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import shared.Model.CategoryFood;
import shared.Model.Food;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author admin
 */
public class IventoryGui extends javax.swing.JPanel {

    /**
     * Creates new form IventoryGui
     */
    private int currentCategoryId = -1;

    public IventoryGui() {

        initComponents();
        displayCategory();
        jTable2.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showFoodImage();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "category ID", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("thêm loại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Category");

        jLabel2.setText("..............");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price In", "Quantity", "Price Out"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("thêm món");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("xóa món");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("thêm ảnh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("xóa ảnh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("chọn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("chỉnh số lượng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Không có ảnh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton6)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //add category
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String categoryName = JOptionPane.showInputDialog(null);
        if (categoryName == null || categoryName.trim().isEmpty()) {
            return;
        }
        try {
            CategoryFood category = new CategoryFood();
            category.setTen(categoryName);
            Request req = new Request("INSERT CATEGORY", category);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //delete category
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn Category cần xóa");
            return;
        }
        try {
            int categoryID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            CategoryFood category = new CategoryFood();
            category.setId(categoryID);
            Request req = new Request("DELETE CATEGORY", category);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory(); //xóa xong hiển thị lại danh sách category
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //choose category
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn category!");
            return;
        }
        try {
            int categoryId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String categoryName = jTable1.getValueAt(row, 1).toString();
            currentCategoryId = categoryId;
            jLabel2.setText(categoryName);
            displayFood(categoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    //delete food
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần xóa");
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE FOOD", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId);
                jTable2.clearSelection();
                jLabel3.setIcon(null);
                jLabel3.setText("không có ảnh");
            }
            JOptionPane.showMessageDialog(this, res.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    //add food
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        try {
            String name = JOptionPane.showInputDialog(this, "Nhập tên món ăn:");
            if (name == null || name.trim().isEmpty()) {
                return;
            }
            String priceinStr = JOptionPane.showInputDialog(this, "giá nhập:");
            if (priceinStr == null || priceinStr.trim().isEmpty()) {
                return;
            }
            String numberStr = JOptionPane.showInputDialog(this, "Nhập số lượng:");
            if (numberStr == null || numberStr.trim().isEmpty()) {
                return;
            }
            String priceoutStr = JOptionPane.showInputDialog(this, "giá bán:");
            if (priceoutStr == null || priceoutStr.trim().isEmpty()) {
                return;
            }
            int numbers = Integer.parseInt(numberStr);
            BigDecimal pricein = new BigDecimal(priceinStr);
            BigDecimal priceout = new BigDecimal(priceoutStr);
            Food food = new Food();
            food.setNameFood(name);
            food.setPriceIn(pricein);
            food.setPriceOut(priceout);
            food.setIdcategory(currentCategoryId);
            food.setNumbers(numbers);
            Request req = new Request("INSERT FOOD", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayFood(currentCategoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //add image
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần thêm ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            // file chooser
            JFileChooser jf = new JFileChooser();
            jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
            // filter ảnh
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg");
            jf.setFileFilter(filter);
            // mở dialog
            int result = jf.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = jf.getSelectedFile();
                // đọc file thành byte[]
                byte[] imageData = Files.readAllBytes(file.toPath());
                // tạo object food
                Food food = new Food();
                food.setId(foodId);
                food.setImageData(imageData);
                // gửi tên file
                food.setImagePath(file.getName());
                // request
                Request req = new Request("UPLOAD IMAGE", food);
                // gửi server
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
                if (res.getStatus().equals("SUCCESS")) {
                    JOptionPane.showMessageDialog(this, "Upload ảnh thành công");
                    showFoodImage();
                } else {
                    JOptionPane.showMessageDialog(this, "Upload ảnh thất bại");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    //delete image
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần xóa ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE IMAGE", food);
            // gửi server
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            if (res.getStatus().equals("SUCCESS")) {
                JOptionPane.showMessageDialog(this, "xóa ảnh thành công");
                showFoodImage();
            } else {
                JOptionPane.showMessageDialog(this, "xóa ảnh thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    //edit quantity
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn cần sửa số lượng!");
            return;
        }
        try {
            // Lấy ID món ăn và số lượng hiện tại từ bảng
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            String currentQty = jTable2.getValueAt(row, 3).toString();
            // Mở hộp thoại để người dùng nhập số lượng mới
            String input = JOptionPane.showInputDialog(this, "Nhập số lượng mới:", currentQty);
            if (input == null || input.trim().isEmpty()) {
                return;
            }
            int newQuantity = Integer.parseInt(input);
            if (newQuantity < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng không được là số âm!");
                return;
            }
            // Tạo đối tượng Food để gửi lên server
            Food food = new Food();
            food.setId(foodId);
            food.setNumbers(newQuantity);
            // Gửi yêu cầu cập nhật lên server
            Request req = new Request("UPDATE QUANTITY", food);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            // Nếu thành công thì làm mới lại danh sách trên bảng
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên hợp lệ.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public void showFoodImage() {
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Request req = new Request("SHOW IMAGE", foodId);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            if (res.getStatus().equals("SUCCESS")) {
                Food food = (Food) res.getData();
                byte[] imageBytes = food.getImageData();
                ImageIcon icon = new ImageIcon(imageBytes);
                // resize ảnh
                Image img = icon.getImage();
                Image scaled = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
                jLabel3.setIcon(new ImageIcon(scaled));
                jLabel3.setText("");
            } else {
                jLabel3.setIcon(null);
                jLabel3.setText("Không có ảnh");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void displayFood(int categoryId) {
        try {
            Request req = new Request("SELECT FOOD BY CATEGORY", categoryId);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            if ("SUCCESS".equals(res.getStatus())) {
                DecimalFormat df = new DecimalFormat("###,###");
                ArrayList<Food> list = (ArrayList<Food>) res.getData();
                for (Food f : list) {
                    String priceInFormatted = (f.getPriceIn() != null) ? df.format(f.getPriceIn()) : "0";
                    String priceOutFormatted = (f.getPriceOut() != null) ? df.format(f.getPriceOut()) : "0";
                    model.addRow(new Object[]{
                        f.getId(),
                        f.getNameFood(),
                        priceInFormatted,
                        f.getNumbers(),
                        priceOutFormatted});
                }
            } else {
                JOptionPane.showMessageDialog(this, res.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void displayCategory() {
        try {
            Request req = new Request("SELECT CATEGORY", null);
            ClientConnection.getOut().writeObject(req);
            ClientConnection.getOut().flush();
            Response res = (Response) ClientConnection.getIn().readObject();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            switch (res.getStatus()) {
                case "SUCCESS": {
                    ArrayList<CategoryFood> list = (ArrayList<CategoryFood>) res.getData();
                    for (CategoryFood c : list) {
                        model.addRow(new Object[]{c.getId(), c.getTen()});
                    }
                    break;
                }
                case "NO CATEGORY": {
                    JOptionPane.showMessageDialog(this, "Chưa có category nào!");
                    break;
                }
                default: {
                    JOptionPane.showMessageDialog(this, res.getMessage());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
