package Client.ManagerGUI;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.TableFood;
/**
 *
 * @author HAI
 */
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author HAI
 */
public class TabeManager extends javax.swing.JFrame {

    private ObjectInputStream in;
    private ObjectOutputStream out;

    /**
     * Creates new form Table
     */
    public TabeManager(ObjectInputStream in, ObjectOutputStream out) {
        this.in = in;
        this.out = out;
        initComponents();
        try {
            load();
        } catch (IOException ex) {
            Logger.getLogger(TabeManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TabeManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Thêm bàn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // thêm bàn
        try {
            TableFood tbf = new TableFood();
            String name = JOptionPane.showInputDialog(this, "Nhập tên bàn");

            if (name == null || name.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên bàn không hợp lệ");
                return;
            }

            tbf.setName(name.trim());
            tbf.setStatus("Trống");
            Request req = new Request("ADD TABLE", tbf);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            load();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Delete Table
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn bàn cần xóa");
        } else {
            try {
                // Nếu Bàn đang có người ngồi thì không xóa được
                String status = jTable2.getValueAt(row, 2).toString();
                if (status.trim().equalsIgnoreCase("Có người")) {
                    JOptionPane.showMessageDialog(this, "bàn có người, không xóa được");
                    return;
                }
                // Lấy ID từ textfield
                int id = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
                // Tạo object gửi server
                TableFood tbf = new TableFood();
                tbf.setId(id);
                // Gửi request xóa
                Request req = new Request("DELETE TABLE", tbf);
                out.writeObject(req);
                out.flush();
                // Nhận phản hồi
                Response res = (Response) in.readObject();
                JOptionPane.showMessageDialog(this, res.getMessage());
                // Nếu xóa thành công thì load lại bảng
                if (res.getStatus().equals("SUCCESS")) {
                    load();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_jButton2MouseClicked

    public void load() throws IOException, ClassNotFoundException {
        try {
            Request req = new Request("GET TABLES", null);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            List<TableFood> list = (List<TableFood>) res.getData();
            if (list == null) {
                return;
            }
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[]{
                    list.get(i).getId(),
                    list.get(i).getName(),
                    list.get(i).getStatus()
                });
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
