/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.ManagerGUI;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.TableFood;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author admin
 */
public class TableGui extends javax.swing.JPanel {
    private ObjectInputStream in;
    private ObjectOutputStream out;
    
    /**
     * Creates new form TableGui
     */
    public TableGui(ObjectInputStream in, ObjectOutputStream out) {
        initComponents();
        this.in = in;
        this.out = out;
        try {
            load();
        } catch (IOException ex) {
            Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Table", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("thêm bàn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xóa bàn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //thêm bàn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            TableFood tbf = new TableFood();
            String name = JOptionPane.showInputDialog(this, "Nhập tên bàn");

            if (name == null || name.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên bàn không hợp lệ");
                return;
            }

            tbf.setName(name.trim());
            tbf.setStatus("Trống");
            Request req = new Request("ADD TABLE", tbf);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            load();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //xóa bàn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Delete Table
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn bàn cần xóa");
        } else {
            try {
                // Nếu Bàn đang có người ngồi thì không xóa được
                String status = jTable1.getValueAt(row, 2).toString();
                if (status.trim().equalsIgnoreCase("Có người")) {
                    JOptionPane.showMessageDialog(this, "bàn có người, không xóa được");
                    return;
                }
                // Lấy ID từ textfield
                int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                // Tạo object gửi server
                TableFood tbf = new TableFood();
                tbf.setId(id);
                // Gửi request xóa
                Request req = new Request("DELETE TABLE", tbf);
                out.writeObject(req);
                out.flush();
                // Nhận phản hồi
                Response res = (Response) in.readObject();
                JOptionPane.showMessageDialog(this, res.getMessage());
                // Nếu xóa thành công thì load lại bảng
                if (res.getStatus().equals("SUCCESS")) {
                    load();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void load() throws IOException, ClassNotFoundException {
        try {
            Request req = new Request("GET TABLES", null);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            List<TableFood> list = (List<TableFood>) res.getData();
            if (list == null) {
                return;
            }
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[]{
                    list.get(i).getId(),
                    list.get(i).getName(),
                    list.get(i).getStatus()
                });
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
