package Client.ManagerGUI;

import Client.ClientConnection;
import com.formdev.flatlaf.FlatLightLaf;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.TableFood;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author ADMIN
 */
public class TableGui extends javax.swing.JPanel {

    private List<TableFood> tableList;
    /**
     * Creates new form TableGui1
     */
    public TableGui() {
        try {
            FlatLightLaf.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();

        Tong.putClientProperty("FlatLaf.style", "background: #FFFFFF; border: 1,1,1,1,#E6D5C3,,16; arc: 16");

        Trong.putClientProperty("FlatLaf.style", "background: #FFFFFF; border: 1,1,1,1,#E6D5C3,,16; arc: 16");

        CoNguoi.putClientProperty("FlatLaf.style", "background: #FFFFFF; border: 1,1,1,1,#E6D5C3,,16; arc: 16");
        load();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        Tong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Trong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CoNguoi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        ToolBarPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        btnThemBan = new javax.swing.JButton();
        xoaBan = new javax.swing.JButton();
        scrollDsBan = new javax.swing.JScrollPane();
        panelDsBan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 235, 230));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        TopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 10, 25));
        TopPanel.setOpaque(false);
        TopPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 46, 43));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tablet.png"))); // NOI18N
        jLabel2.setText("Quản lý bàn");
        jLabel2.setIconTextGap(10);
        TopPanel.add(jLabel2, java.awt.BorderLayout.NORTH);

        pnlThongKe.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        pnlThongKe.setMinimumSize(new java.awt.Dimension(100, 100));
        pnlThongKe.setOpaque(false);
        pnlThongKe.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        Tong.setMaximumSize(new java.awt.Dimension(180, 70));
        Tong.setMinimumSize(new java.awt.Dimension(180, 70));
        Tong.setPreferredSize(new java.awt.Dimension(100, 50));
        Tong.setLayout(new javax.swing.BoxLayout(Tong, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Tổng số bàn");
        Tong.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("18");
        Tong.add(jLabel3);

        pnlThongKe.add(Tong);

        Trong.setLayout(new javax.swing.BoxLayout(Trong, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("Đang trống");
        Trong.add(jLabel4);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 125, 50));
        jLabel11.setText("18");
        Trong.add(jLabel11);

        pnlThongKe.add(Trong);

        CoNguoi.setLayout(new javax.swing.BoxLayout(CoNguoi, javax.swing.BoxLayout.Y_AXIS));

        jLabel7.setText("Có người");
        CoNguoi.add(jLabel7);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(139, 34, 34));
        jLabel12.setText("18");
        CoNguoi.add(jLabel12);

        pnlThongKe.add(CoNguoi);

        TopPanel.add(pnlThongKe, java.awt.BorderLayout.CENTER);

        add(TopPanel, java.awt.BorderLayout.PAGE_START);

        CenterPanel.setOpaque(false);
        CenterPanel.setLayout(new java.awt.BorderLayout());

        ToolBarPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        ToolBarPanel.setOpaque(false);
        ToolBarPanel.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(74, 46, 43));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu (3).png"))); // NOI18N
        jLabel8.setText("Danh sách bàn");
        jLabel8.setIconTextGap(8);
        ToolBarPanel.add(jLabel8, java.awt.BorderLayout.WEST);

        panelButton.setOpaque(false);

        btnThemBan.setBackground(new java.awt.Color(74, 46, 43));
        btnThemBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemBan.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu (4).png"))); // NOI18N
        btnThemBan.setText("Thêm bàn");
        btnThemBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemBan.setIconTextGap(8);
        btnThemBan.setMaximumSize(new java.awt.Dimension(110, 32));
        btnThemBan.setMinimumSize(new java.awt.Dimension(110, 32));
        btnThemBan.setPreferredSize(new java.awt.Dimension(110, 28));
        btnThemBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanActionPerformed(evt);
            }
        });
        panelButton.add(btnThemBan);

        xoaBan.setBackground(new java.awt.Color(139, 34, 34));
        xoaBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xoaBan.setForeground(new java.awt.Color(255, 255, 255));
        xoaBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash-bin.png"))); // NOI18N
        xoaBan.setText("Xóa bàn");
        xoaBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xoaBan.setIconTextGap(8);
        xoaBan.setPreferredSize(new java.awt.Dimension(110, 28));
        xoaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBanActionPerformed(evt);
            }
        });
        panelButton.add(xoaBan);

        ToolBarPanel.add(panelButton, java.awt.BorderLayout.EAST);

        CenterPanel.add(ToolBarPanel, java.awt.BorderLayout.NORTH);

        panelDsBan.setBackground(new java.awt.Color(245, 235, 230));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING);
        flowLayout1.setAlignOnBaseline(true);
        panelDsBan.setLayout(flowLayout1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Table", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelDsBan.add(jScrollPane1);

        scrollDsBan.setViewportView(panelDsBan);

        CenterPanel.add(scrollDsBan, java.awt.BorderLayout.CENTER);

        add(CenterPanel, java.awt.BorderLayout.CENTER);

        BotPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        BotPanel.setOpaque(false);
        BotPanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exclamation.png"))); // NOI18N
        jLabel9.setText("Chọn bàn rồi nhấn Xóa bàn");
        jLabel9.setIconTextGap(8);
        BotPanel.add(jLabel9, java.awt.BorderLayout.WEST);

        jLabel10.setText("Trống        Có người");
        BotPanel.add(jLabel10, java.awt.BorderLayout.EAST);

        add(BotPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    
    private void xoaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBanActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn cần xóa");
            return;
        }
        // Kiểm tra trạng thái bàn
        String status = jTable1.getValueAt(row, 2).toString();
        if (status.trim().equalsIgnoreCase("Có người")) {
            JOptionPane.showMessageDialog(this, "Bàn đang có người, không xóa được");
            return;
        }
        try {
            int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            TableFood tbf = new TableFood();
            tbf.setId(id);

            // Gửi request thông qua ClientConnection
            Request req = new Request("DELETE TABLE", tbf);
            Response res = (Response) ClientConnection.sendRequest(req);
            JOptionPane.showMessageDialog(this, res.getMessage());
            // Nếu xóa thành công thì load lại bảng
            if ("SUCCESS".equals(res.getStatus())) {
                load();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa bàn: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_xoaBanActionPerformed

    private void btnThemBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanActionPerformed
        try {
            TableFood tbf = new TableFood();
            String name = JOptionPane.showInputDialog(this, "Nhập tên bàn");

            if (name == null || name.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên bàn không hợp lệ");
                return;
            }
            tbf.setName(name.trim());
            tbf.setStatus("Trống");
            Request req = new Request("ADD TABLE", tbf);
            Response res = (Response) ClientConnection.sendRequest(req);
            JOptionPane.showMessageDialog(this, res.getMessage());
            load();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemBanActionPerformed

    public void load() {
        try {
            Request req = new Request("GET TABLES", null);
            // Sử dụng phương thức tập trung thay vì gọi trực tiếp out/in
            Response res = (Response) ClientConnection.sendRequest(req);

            if ("SUCCESS".equals(res.getStatus())) {
                tableList = (List<TableFood>) res.getData();
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                if (tableList != null) {
                    for (TableFood tf : tableList) {
                        model.addRow(new Object[]{tf.getId(), tf.getName(), tf.getStatus()});
                    }
                }
                updateThongKe(tableList);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
        }
    }
    private void updateThongKe(List<TableFood> list) {
    int total = 0;
    int trong = 0;
    int coNguoi = 0;

    if (list != null) {
        for (TableFood tf : list) {
            total++;

            if (tf.getStatus() != null &&
                tf.getStatus().trim().equalsIgnoreCase("Trống")) {
                trong++;
            } else {
                coNguoi++;
            }
        }
    }

    jLabel3.setText(String.valueOf(total));
    jLabel11.setText(String.valueOf(trong));
    jLabel12.setText(String.valueOf(coNguoi));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel CoNguoi;
    private javax.swing.JPanel Tong;
    private javax.swing.JPanel ToolBarPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel Trong;
    private javax.swing.JButton btnThemBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelDsBan;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JScrollPane scrollDsBan;
    private javax.swing.JButton xoaBan;
    // End of variables declaration//GEN-END:variables
}
