package Client.StaffGUI;

import Client.ClientConnection;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.*;
import shared.Model.*;
import shared.RequestResponse.*;

/**
 *
 * @author admin
 */
public class FoodGUI extends javax.swing.JPanel { //chịu trách nhiệm hiển thị danh sách món ăn

    /**
     * Creates new form FoodGUI
     */
    private JPanel categoryPanel;
    private JPanel foodPanel;
    private OrderGUI orderGuiRef; //tham chiếu đến order
    public FoodGUI() {
        initComponents();
        setLayout(new BorderLayout());
        categoryPanel = new JPanel();
        categoryPanel.setLayout(new GridLayout(0, 1, 5, 5));
        foodPanel = new JPanel();
        foodPanel.setLayout(new GridLayout(0, 3, 10, 10));
        add(categoryPanel, BorderLayout.WEST);
        add(new JScrollPane(foodPanel), BorderLayout.CENTER);
        loadCategories();
    }
    public void setOrderGui(OrderGUI orderGui) {
        this.orderGuiRef = orderGui;
    }
    public void loadCategories() {
        new SwingWorker<List<CategoryFood>, Void>() {
            //swingworker: chạy tác vụ nặng background thread
            @Override
            protected List<CategoryFood> doInBackground() throws Exception {//làm trong background
                // Sử dụng lớp ClientConnection đã đồng bộ hóa
                Response res = (Response) ClientConnection.sendRequest(new Request("SELECT CATEGORY", null));
                return (List<CategoryFood>) res.getData();
            }

            @Override
            protected void done() {//quay lại UI
                try {
                    List<CategoryFood> list = get();
                    categoryPanel.removeAll();
                    for (CategoryFood c : list) {
                        JButton btn = new JButton(c.getTen());
                        btn.addActionListener(e -> loadFoodsByCategory(c.getId()));
                        categoryPanel.add(btn);
                    }
                    categoryPanel.revalidate();
                    categoryPanel.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.execute();
    }

    public void loadFoodsByCategory(int categoryId) {
        new SwingWorker<List<Food>, Void>() {
            @Override
            protected List<Food> doInBackground() throws Exception {
                // Sử dụng lớp ClientConnection đã đồng bộ hóa
                Response res = (Response) ClientConnection.sendRequest(new Request("SELECT FOOD BY CATEGORY", categoryId));
                return (List<Food>) res.getData();
            }
            @Override
            protected void done() {
                try {
                    List<Food> foods = get();
                    foodPanel.removeAll();
                    for (Food f : foods) {
                        JButton btn = createFoodButton(f);
                        foodPanel.add(btn);
                    }
                    foodPanel.revalidate();
                    foodPanel.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.execute();
    }

    private JButton createFoodButton(Food f) {
        JButton btn = new JButton();

        // 1. Cấu hình hiển thị Text
        btn.setText("<html><center>" + f.getNameFood() + "<br/>" + f.getPriceOut() + "</center></html>");
        btn.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);

        // 2. Cấu hình hiển thị Ảnh (Đọc từ đường dẫn hệ thống)
        String imagePath = f.getImagePath();
        if (imagePath != null && !imagePath.isEmpty()) {
            // Thay đổi đường dẫn này thành thư mục chứa ảnh thực tế của bạn
            String fullPath = System.getProperty("user.dir") + "/" + imagePath;
            java.io.File imgFile = new java.io.File(fullPath);
            if (imgFile.exists()) {
                ImageIcon icon = new ImageIcon(fullPath);
                Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                btn.setIcon(new ImageIcon(img));
            } else {
                btn.setText("<html><center>No Image<br/>" + f.getNameFood() + "</center></html>");
            }
        }
        btn.addActionListener(e -> {
                if (orderGuiRef != null) {
                    orderGuiRef.addFoodToTempList(f);
                }
            });
            return btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
