/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.StaffGUI;

import Client.ClientConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import shared.Model.BillInfor;
import shared.Model.Food;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author admin
 */
public class OrderGUI2 extends javax.swing.JPanel implements FoodAdditionListener {

    private OrderUpdateListener listener;
    private List<BillInfor> tempOrderList = new ArrayList<>();
    private BillInfor selectedItem = null;

    /**
     * Creates new form OrderGUI2
     */
    public OrderGUI2() {
        initComponents();
        setupTableStyle();
    }

    public void setOrderUpdateListener(OrderUpdateListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SouthPanel = new javax.swing.JPanel();
        pnlTong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 235, 230));
        setLayout(new java.awt.BorderLayout());

        headPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        headPanel.setOpaque(false);
        headPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 46, 43));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/grocery-store.png"))); // NOI18N
        jLabel2.setText("Giỏ hàng");
        jLabel2.setIconTextGap(8);
        headPanel.add(jLabel2);

        add(headPanel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        SouthPanel.setOpaque(false);
        SouthPanel.setLayout(new java.awt.BorderLayout());

        pnlTong.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        pnlTong.setOpaque(false);
        pnlTong.setLayout(new javax.swing.BoxLayout(pnlTong, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 46, 43));
        jLabel1.setText("Tổng tiền");
        pnlTong.add(jLabel1);

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(87, 223, 77));
        jLabelTotal.setText("....");
        jLabelTotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelTotal.setIconTextGap(8);
        pnlTong.add(jLabelTotal);

        SouthPanel.add(pnlTong, java.awt.BorderLayout.NORTH);

        pnlButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        pnlButton.setOpaque(false);
        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        jButton1.setBackground(new java.awt.Color(74, 46, 43));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/confirm.png"))); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.setIconTextGap(8);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlButton.add(jButton1);

        jButton2.setBackground(new java.awt.Color(74, 46, 43));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash-bin.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.setIconTextGap(8);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlButton.add(jButton2);

        jButton3.setBackground(new java.awt.Color(74, 46, 43));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash.png"))); // NOI18N
        jButton3.setText("Xóa toàn bộ");
        jButton3.setIconTextGap(8);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlButton.add(jButton3);

        SouthPanel.add(pnlButton, java.awt.BorderLayout.SOUTH);

        add(SouthPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    //xóa món đang chọn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            tempOrderList.remove(selectedRow);
            updateTable(tempOrderList);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn món cần xóa!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //xác nhận tạo hóa đơn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tempOrderList.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Danh sách món đang trống!");
            return;
        }

        jButton1.setEnabled(false);
        try {
            //tổng giá tiền
            java.math.BigDecimal totalBill = java.math.BigDecimal.ZERO;
            for (BillInfor item : tempOrderList) {
                totalBill = totalBill.add(item.getPrice().multiply(new java.math.BigDecimal(item.getQuantity())));
            }

            Object[] data = {
                tempOrderList,
                totalBill
            };
            Request req = new Request("CREATE ORDER WITH NO TABLE", data);
            Response res = (Response) ClientConnection.sendRequest(req);
            if (res != null && "SUCCESS".equals(res.getStatus())) {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công");
                tempOrderList.clear();
                updateTable(tempOrderList);
                if (listener != null) {
                    listener.onOrderPlacedSuccessfully();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thất bại");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //xóa hết
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tempOrderList.clear();
        updateTable(tempOrderList);
    }//GEN-LAST:event_jButton3ActionPerformed
    public void updateTable(List<BillInfor> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        java.math.BigDecimal grandTotal = java.math.BigDecimal.ZERO;

        for (BillInfor item : list) {
            java.math.BigDecimal total = item.getPrice().multiply(new java.math.BigDecimal(item.getQuantity()));
            grandTotal = grandTotal.add(total);
            model.addRow(new Object[]{item.getFoodName(), item.getPrice(), item.getQuantity(), total});
        }
        // Cập nhật tổng tiền vào label (Giả sử bạn đã thêm jLabelTotal trong thiết kế)
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icon/money (2).png"));
        jLabelTotal.setIcon(icon);
        jLabelTotal.setText(grandTotal.toString());
    }

// Thêm hàm này vào class OrderGUI2
    public void addFoodToTempList(Food food) {
        boolean found = false;
        for (BillInfor item : tempOrderList) {
            if (item.getIdFood() == food.getId()) {
                item.setQuantity(item.getQuantity() + 1);
                found = true;
                break;
            }
        }
        if (!found) {
            tempOrderList.add(new BillInfor(0, -1, food.getId(), food.getNameFood(), 1, food.getPriceOut()));
        }
        updateTable(tempOrderList);
    }

    private void setupTableStyle() {

        // Header
        jTable1.getTableHeader().setBackground(
                new java.awt.Color(74, 46, 43));

        jTable1.getTableHeader().setForeground(
                java.awt.Color.WHITE);

        jTable1.getTableHeader().setFont(
                new java.awt.Font("Segoe UI",
                        java.awt.Font.BOLD,
                        14));

        jTable1.getTableHeader().setPreferredSize(
                new java.awt.Dimension(100, 38));

        // Table
        jTable1.setRowHeight(36);

        jTable1.setFont(
                new java.awt.Font("Segoe UI",
                        java.awt.Font.PLAIN,
                        14));

        jTable1.setBackground(java.awt.Color.WHITE);

        jTable1.setGridColor(
                new java.awt.Color(225, 225, 225));

        jTable1.setShowVerticalLines(false);

        jTable1.setSelectionBackground(
                new java.awt.Color(225, 215, 210));

        jTable1.setSelectionForeground(
                new java.awt.Color(74, 46, 43));

        // ScrollPane
        jScrollPane1.setBorder(
                BorderFactory.createLineBorder(
                        new java.awt.Color(216, 154, 43),
                        2));

        jScrollPane1.getViewport().setBackground(
                java.awt.Color.WHITE);

        // Căn giữa các cột số
        javax.swing.table.DefaultTableCellRenderer center
                = new javax.swing.table.DefaultTableCellRenderer();

        center.setHorizontalAlignment(
                javax.swing.SwingConstants.CENTER);

        jTable1.getColumnModel()
                .getColumn(1)
                .setCellRenderer(center);

        jTable1.getColumnModel()
                .getColumn(2)
                .setCellRenderer(center);

        jTable1.getColumnModel()
                .getColumn(3)
                .setCellRenderer(center);

        // Width
        jTable1.getColumnModel()
                .getColumn(0)
                .setPreferredWidth(250);

        jTable1.getColumnModel()
                .getColumn(1)
                .setPreferredWidth(120);

        jTable1.getColumnModel()
                .getColumn(2)
                .setPreferredWidth(80);

        jTable1.getColumnModel()
                .getColumn(3)
                .setPreferredWidth(150);

        // Zebra Row
        jTable1.setDefaultRenderer(
                Object.class,
                new javax.swing.table.DefaultTableCellRenderer() {

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                java.awt.Component c
                        = super.getTableCellRendererComponent(
                                table,
                                value,
                                isSelected,
                                hasFocus,
                                row,
                                column);

                if (!isSelected) {

                    if (row % 2 == 0) {
                        c.setBackground(java.awt.Color.WHITE);
                    } else {
                        c.setBackground(
                                new java.awt.Color(248, 245, 243));
                    }

                    c.setForeground(
                            new java.awt.Color(74, 46, 43));
                }

                return c;
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlTong;
    // End of variables declaration//GEN-END:variables
}
