/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.StaffGUI;

import Client.ClientConnection;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.math.BigDecimal;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import shared.Model.BillInfor;
import shared.Model.Bill;
import shared.Model.Food;
import shared.RequestResponse.Request;
import shared.RequestResponse.Response;

/**
 *
 * @author admin
 */
public class OrderGUI2 extends javax.swing.JPanel implements FoodAdditionListener {

    private OrderUpdateListener listener;
    private List<BillInfor> tempOrderList = new ArrayList<>();
    private List<BillInfor> pendingOrder = new ArrayList<>();
    private BigDecimal pendingTotal = BigDecimal.ZERO;

    /**
     * Creates new form OrderGUI2
     */
    public OrderGUI2() {
        initComponents();
    }

    public void setOrderUpdateListener(OrderUpdateListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tên", "đơn giá", "số lươngj", "thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("xóa toàn bộ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelTotal.setText("....");

        jLabel1.setText("tổng tiền");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //xóa món đang chọn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            tempOrderList.remove(selectedRow);
            updateTable(tempOrderList);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn món cần xóa!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //xác nhận tạo hóa đơn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tempOrderList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách món đang trống!");
            return;
        }

        jButton1.setEnabled(false);

        try {
            BigDecimal totalBill = BigDecimal.ZERO;

            for (BillInfor item : tempOrderList) {
                totalBill = totalBill.add(
                        item.getPrice().multiply(
                                BigDecimal.valueOf(item.getQuantity())
                        )
                );
            }

            pendingOrder = new ArrayList<>(tempOrderList);
            pendingTotal = totalBill;

            showQrPayment(pendingOrder, pendingTotal);

        } finally {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //xóa hết
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tempOrderList.clear();
        updateTable(tempOrderList);
    }//GEN-LAST:event_jButton3ActionPerformed
    public void updateTable(List<BillInfor> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        java.math.BigDecimal grandTotal = java.math.BigDecimal.ZERO;

        for (BillInfor item : list) {
            java.math.BigDecimal total = item.getPrice().multiply(new java.math.BigDecimal(item.getQuantity()));
            grandTotal = grandTotal.add(total);
            model.addRow(new Object[]{item.getFoodName(), item.getPrice(), item.getQuantity(), total});
        }
        // Cập nhật tổng tiền vào label (Giả sử bạn đã thêm jLabelTotal trong thiết kế)
        jLabelTotal.setText("Tổng cộng: " + grandTotal.toString() + " VNĐ");
    }
// Thêm hàm này vào class OrderGUI2

    private void showQrPayment(List<BillInfor> details,
            java.math.BigDecimal totalAmount) {
        new Thread(() -> {
            try {

                String qrUrl
                        = "https://img.vietqr.io/image/TCB-6042088888-compact2.png"
                        + "?amount=" + totalAmount
                        + "&addInfo=ORDER_PAYMENT";

                BufferedImage qrImage
                        = ImageIO.read(new URL(qrUrl));

                Image scaled
                        = qrImage.getScaledInstance(
                                400,
                                500,
                                Image.SCALE_SMOOTH);

                ImageIcon icon
                        = new ImageIcon(scaled);

                SwingUtilities.invokeLater(() -> {

                    JPanel panel
                            = new JPanel(
                                    new GridLayout(1, 2, 10, 10));

                    // ======================
                    // BÊN TRÁI: HÓA ĐƠN
                    // ======================
                    JTextArea txtBill
                            = new JTextArea();

                    txtBill.setEditable(false);

                    txtBill.setFont(
                            new java.awt.Font(
                                    "Monospaced",
                                    java.awt.Font.PLAIN,
                                    14));

                    txtBill.append("CHI TIẾT ĐƠN HÀNG\n\n");

                    for (BillInfor item : details) {

                        java.math.BigDecimal lineTotal
                                = item.getPrice().multiply(
                                        new java.math.BigDecimal(
                                                item.getQuantity()));

                        txtBill.append(
                                String.format(
                                        "%-20s x%-3d %10s\n",
                                        item.getFoodName(),
                                        item.getQuantity(),
                                        lineTotal));
                    }
                    txtBill.append(
                            "\n------------------------------\n");
                    txtBill.append(
                            "TỔNG TIỀN: "
                            + totalAmount
                            + " VNĐ");

                    JScrollPane billScroll
                            = new JScrollPane(txtBill);

                    JPanel leftPanel
                            = new JPanel(
                                    new BorderLayout());

                    leftPanel.add(
                            billScroll,
                            BorderLayout.CENTER);

                    // ======================
                    // BÊN PHẢI: QR
                    // ======================
                    JLabel qrLabel
                            = new JLabel(icon);

                    qrLabel.setHorizontalAlignment(
                            SwingConstants.CENTER);

                    JPanel rightPanel
                            = new JPanel(
                                    new BorderLayout());

                    rightPanel.add(
                            qrLabel,
                            BorderLayout.CENTER);

                    panel.add(leftPanel);
                    panel.add(rightPanel);

                    int result = JOptionPane.showConfirmDialog(
                            OrderGUI2.this,
                            panel,
                            "Thanh toán QR",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.PLAIN_MESSAGE
                    );

                    if (result == JOptionPane.YES_OPTION) {
                        handlePaymentSuccess();
                    } else {
                        JOptionPane.showMessageDialog(this, "Đã hủy thanh toán!");
                    }

                });

            } catch (Exception ex) {
                ex.printStackTrace();

                SwingUtilities.invokeLater(()
                        -> JOptionPane.showMessageDialog(
                                OrderGUI2.this,
                                "Không thể tạo QR!",
                                "Lỗi",
                                JOptionPane.ERROR_MESSAGE));
            }
        }).start();
    }

    private void handlePaymentSuccess() {

        try {
            Object[] data = {
                pendingOrder,
                pendingTotal
            };

            Request req = new Request(
                    "CREATE ORDER WITH NO TABLE",
                    data
            );
            Response res = (Response) ClientConnection.sendRequest(req);
            if (res == null || !"SUCCESS".equals(res.getStatus())) {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại!");
                return;
            }
            int billId = ((Number) res.getData()).intValue();
            Bill bill = new Bill();
            bill.setId(billId);
            bill.setTotalPrice(pendingTotal);

            shared.PrintInvoice.saveInvoice(bill, pendingOrder);

            JOptionPane.showMessageDialog(this, "Thanh toán thành công!");

            tempOrderList.clear();
            pendingOrder.clear();
            pendingTotal = BigDecimal.ZERO;

            updateTable(new ArrayList<>());
            if (listener != null) {
                listener.onOrderPlacedSuccessfully();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void addFoodToTempList(Food food) {
        boolean found = false;
        for (BillInfor item : tempOrderList) {
            if (item.getIdFood() == food.getId()) {
                item.setQuantity(item.getQuantity() + 1);
                found = true;
                break;
            }
        }
        if (!found) {
            tempOrderList.add(new BillInfor(0, -1, food.getId(), food.getNameFood(), 1, food.getPriceOut()));
        }
        updateTable(tempOrderList);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
