package Client.StaffGUI;

import Client.ClientConnection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import shared.Model.BillInfor;
import shared.Model.Food;
import shared.RequestResponse.*;

/**
 *
 * @author admin
 */
public class OrderGUI extends javax.swing.JPanel {

    /**
     * Creates new form OrderGUI
     */
    private int currentTableId;
    private List<BillInfor> tempOrderList = new ArrayList<>();
    private OrderUpdateListener listener;


    public OrderGUI() {
        initComponents();
    }

    public void setCurrentTableId(int id) {
        this.currentTableId = id;
        if (id > 0) {
            jLabel2.setText(String.valueOf(id));
        } else {
            jLabel2.setText("Chưa chọn");
        }
        updateTable(tempOrderList);
    }
    public void setOrderUpdateListener(OrderUpdateListener listener) {
        this.listener = listener;
    }
    public void addFoodToTempList(Food food) {
        // Kiểm tra xem món đã có trong list chưa, nếu có thì tăng quantity
        boolean found = false;
        for (BillInfor item : tempOrderList) {
            if (item.getIdFood() == food.getId()) {
                item.setQuantity(item.getQuantity() + 1);
                found = true;
                break;
            }
        }
        if (!found) {
            tempOrderList.add(new BillInfor(0, -1, food.getId(), food.getNameFood(), 1, food.getPriceOut()));
        }
        updateTable(tempOrderList); // Cập nhật lên JTable
    }

    public void updateTable(List<BillInfor> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        for (BillInfor item : list) {
            // Giả sử thành tiền = đơn giá * số lượng
            java.math.BigDecimal total = item.getPrice().multiply(new java.math.BigDecimal(item.getQuantity()));
            model.addRow(new Object[]{
                item.getFoodName(),
                item.getPrice(),
                item.getQuantity(),
                total,  
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tên", "Đơn giá", "Số lượng", "thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xóa toàn bộ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("bàn đang chọn:");

        jLabel2.setText("......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tempOrderList.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Danh sách món đang trống!");
            return;
        }
        if (currentTableId <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Chưa chọn bàn!");
            return;
        }
        jButton1.setEnabled(false);
        try {
            //tổng giá tiền
            java.math.BigDecimal totalBill = java.math.BigDecimal.ZERO;
            for (BillInfor item : tempOrderList) {
                totalBill = totalBill.add(item.getPrice().multiply(new java.math.BigDecimal(item.getQuantity())));
            }

            Object[] data = {
            currentTableId,
            tempOrderList,
            totalBill
            };
            Request req = new Request("CREATE ORDER",data);
            Response res = (Response)ClientConnection.sendRequest(req);
            if (res != null && "SUCCESS".equals(res.getStatus())) {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công");
                tempOrderList.clear();
                updateTable(tempOrderList);
                if (listener != null) {
                    listener.onOrderPlacedSuccessfully();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thất bại");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // xóa món hiện tại khỏi danh sách chọn tạm
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            tempOrderList.remove(selectedRow);
            updateTable(tempOrderList);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn món cần xóa!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // xóa sạch
        tempOrderList.clear();
        updateTable(tempOrderList);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
