package Client.StaffGUI;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class StaffGUI extends javax.swing.JFrame {//staff gui: điều phối trung tâm

    private Timer refreshTimer;
    private CardLayout cardLayout;
    private TableGui tablegui;
    private FoodGUI foodgui;
    private OrderGUI ordergui;
    private FoodGUI foodgui2;
    private OrderGUI2 ordergui2;
    private int currentTable = -1; //bàn đang chọn
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffGUI.class.getName());

    /**
     * Creates new form StaffGUI
     */
    public StaffGUI() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);

        // --- 1. TẠO TAB 1 
        tablegui = new TableGui();
        foodgui = new FoodGUI();
        ordergui = new OrderGUI();
        foodgui.setOrderGui(ordergui);

        cardLayout = new CardLayout();
        jPanel4.setLayout(cardLayout);
        jPanel4.add(new javax.swing.JLabel("Vui lòng chọn bàn để xem menu..."), "EMPTY");
        jPanel4.add(foodgui, "MENU_SCREEN");

        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(new JScrollPane(tablegui), BorderLayout.CENTER);

        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(ordergui, BorderLayout.CENTER);

        tablegui.loadTables();
        cardLayout.show(jPanel4, "EMPTY");

        ordergui.setOrderUpdateListener(new OrderUpdateListener() {
            @Override
            public void onOrderPlacedSuccessfully() {
                tablegui.loadTables();
                cardLayout.show(jPanel4, "EMPTY");
                currentTable = -1;
            }
        });

        // --- 2. TẠO TAB 2 
        foodgui2 = new FoodGUI();
        ordergui2 = new OrderGUI2();
        foodgui2.setOrderGui(ordergui2);

        // Cấu hình giao diện jPanel2
        jPanel2.setLayout(new BorderLayout());
        javax.swing.JSplitPane splitPane2 = new javax.swing.JSplitPane(
                javax.swing.JSplitPane.HORIZONTAL_SPLIT,
                new JScrollPane(foodgui2),
                ordergui2
        );
        splitPane2.setDividerLocation(500);
        jPanel2.add(splitPane2, BorderLayout.CENTER);

        // Load dữ liệu
        foodgui.loadCategories();
        foodgui2.loadCategories();

        // --- 3. KHỞI TẠO TIMER ---
        refreshTimer = new Timer(1000, e -> {
            refreshTableData();
        });
        refreshTimer.start();
    }

    private void refreshTableData() {
        // Chỉ reload khi không ở trong quá trình chọn bàn hoặc thao tác quan trọng
        // Để tránh giật lag khi đang chọn món
        tablegui.loadTables();

        // Nếu muốn cập nhật cả đơn hàng của bàn đang chọn
        if (currentTable != -1) {
            tablegui.loadTables();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1120, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Các bàn trong quán:");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(732, 400));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1432, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showMenuForTable(int tableId) {
        this.currentTable = tableId;

        // Gán tableId cho OrderGUI để khi xác nhận nó biết tạo bill cho bàn nào
        ordergui.setCurrentTableId(tableId);

        foodgui.loadFoodsByCategory(1); // Mặc định gọi danh mục đầu tiên 
        cardLayout.show(jPanel4, "MENU_SCREEN");
        ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
