package Client;
import java.awt.Image;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.*;
import shared.RequestResponse.*;
import java.math.BigDecimal;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;

public class CategoryMenu extends javax.swing.JFrame {

    private ObjectInputStream in;
    private ObjectOutputStream out;
    private int currentCategoryId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryMenu.class.getName());

    /**
     * Creates new form Menu
     */
    public CategoryMenu(ObjectInputStream in, ObjectOutputStream out) {
        initComponents();
        this.in = in;
        this.out = out;
        displayCategory();
        jTable2.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showFoodImage();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("add category");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("delete category");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "price", "quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Current category:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("......");

        jButton3.setText("choose category");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("add food");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("delete food");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("add image");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jButton7.setText("delete image");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton4)
                        .addComponent(jButton8)
                        .addComponent(jButton9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //add category
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String categoryName = JOptionPane.showInputDialog(null);
        if (categoryName == null || categoryName.trim().isEmpty()) {
            return;
        }
        try {
            CategoryFood category = new CategoryFood();
            category.setTen(categoryName);
            Request req = new Request("INSERT CATEGORY", category);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //delete category
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn Category cần xóa");
            return;
        }
        try {
            int categoryID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            CategoryFood category = new CategoryFood();
            category.setId(categoryID);
            Request req = new Request("DELETE CATEGORY", category);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory(); //xóa xong hiển thị lại danh sách category
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //chọn category
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn category!");
            return;
        }
        try {
            int categoryId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String categoryName = jTable1.getValueAt(row, 1).toString();
            currentCategoryId = categoryId;
            jLabel2.setText(categoryName);
            displayFood(categoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //add food
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        try {
            String name = JOptionPane.showInputDialog(this, "Nhập tên món ăn:");
            if (name == null || name.trim().isEmpty()) {
                return;
            }
            String priceStr = JOptionPane.showInputDialog(this, "Nhập giá:");
            if (priceStr == null || priceStr.trim().isEmpty()) {
                return;
            }
            String numberStr = JOptionPane.showInputDialog(this, "Nhập số lượng:");
            if (numberStr == null || numberStr.trim().isEmpty()) {
                return;
            }
            int numbers = Integer.parseInt(numberStr);
            BigDecimal price = new BigDecimal(priceStr);
            Food food = new Food();
            food.setNameFood(name);
            food.setPrice(price);
            food.setIdcategory(currentCategoryId);
            food.setNumbers(numbers);
            Request req = new Request("INSERT FOOD", food);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayFood(currentCategoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    //delete food
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn món cần xóa");
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE FOOD", food);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            if ("SUCCESS".equals(res.getStatus())) {
                displayFood(currentCategoryId);
                jTable2.clearSelection();
                jLabel3.setIcon(null);
                jLabel3.setText("không có ảnh");
            }
            JOptionPane.showMessageDialog(this, res.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // add image
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,"Chọn món cần thêm ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            // file chooser
            JFileChooser jf = new JFileChooser();
            jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
            // filter ảnh
            FileNameExtensionFilter filter= new FileNameExtensionFilter("Image Files","jpg","png","jpeg");
            jf.setFileFilter(filter);
            // mở dialog
            int result = jf.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = jf.getSelectedFile();
                // đọc file thành byte[]
                byte[] imageData= Files.readAllBytes(file.toPath());
                // tạo object food
                Food food = new Food();
                food.setId(foodId);
                food.setImageData(imageData);
                // gửi tên file
                food.setImagePath(file.getName());
                // request
                Request req= new Request("UPLOAD IMAGE",food);
                // gửi server
                out.writeObject(req);
                out.flush();
                // nhận response
                Response res= (Response) in.readObject();
                if (res.getStatus().equals("SUCCESS")) {
                    JOptionPane.showMessageDialog(this,"Upload ảnh thành công");
                    showFoodImage();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Upload ảnh thất bại");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // delete image
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,"Chọn món cần xóa ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req= new Request("DELETE IMAGE",food);
            // gửi server
            out.writeObject(req);
            out.flush();
            // nhận response
            Response res= (Response) in.readObject();
            if (res.getStatus().equals("SUCCESS")) {
                JOptionPane.showMessageDialog(this,"xóa ảnh thành công");
                showFoodImage();
            }
            else{
                JOptionPane.showMessageDialog(this,"xóa ảnh thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // increase food
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,"Chọn món cần xóa ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req= new Request("INCREASE FOOD",food);
            // gửi server
            out.writeObject(req);
            out.flush();
            // nhận response
            Response res= (Response) in.readObject();
            if (res.getStatus().equals("SUCCESS")) {
                displayFood(this.currentCategoryId);
                if (row >= 0 && row < jTable2.getRowCount()) {
                    jTable2.setRowSelectionInterval(row, row);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"tăng thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // decrease food
        if (currentCategoryId == -1) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,"Chọn món cần xóa ảnh");
            return;
        }
        try {
            // lấy food id
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req= new Request("DECREASE FOOD",food);
            // gửi server
            out.writeObject(req);
            out.flush();
            // nhận response
            Response res= (Response) in.readObject();
            if (res.getStatus().equals("SUCCESS")) {
                displayFood(this.currentCategoryId);
                if (row >= 0 && row < jTable2.getRowCount()) {
                    jTable2.setRowSelectionInterval(row, row);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"giảm thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed
    public void showFoodImage() {
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Request req = new Request("SHOW IMAGE", foodId);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            if (res.getStatus().equals("SUCCESS")) {
                Food food = (Food) res.getData();
                byte[] imageBytes = food.getImageData();
                ImageIcon icon = new ImageIcon(imageBytes);
                // resize ảnh
                Image img = icon.getImage();
                Image scaled = img.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_SMOOTH);
                jLabel3.setIcon(new ImageIcon(scaled));
                jLabel3.setText("");
            } else {
                jLabel3.setIcon(null);
                jLabel3.setText("Không có ảnh");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    
    public void displayFood(int categoryId) {
        try {
            Request req = new Request("SELECT FOOD BY CATEGORY", categoryId);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            if ("SUCCESS".equals(res.getStatus())) {
                ArrayList<Food> list = (ArrayList<Food>) res.getData();
                for (Food f : list) {
                    model.addRow(new Object[]{
                        f.getId(),
                        f.getNameFood(),
                        f.getPrice(),
                        f.getNumbers()});
                        
                }
            } else {
                JOptionPane.showMessageDialog(this, res.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void displayCategory() {
        try {
            Request req = new Request("SELECT CATEGORY", null);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            switch (res.getStatus()) {
                case "SUCCESS": {
                    ArrayList<CategoryFood> list = (ArrayList<CategoryFood>) res.getData();
                    for (CategoryFood c : list) {
                        model.addRow(new Object[]{
                            c.getId(),
                            c.getTen()
                        });
                    }
                    break;
                }
                case "NO CATEGORY": {
                    JOptionPane.showMessageDialog(this, "Chưa có category nào!");
                    break;
                }
                default: {
                    JOptionPane.showMessageDialog(this, res.getMessage());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
