package Client;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shared.Model.*;
import shared.RequestResponse.*;
import java.math.BigDecimal;

public class CategoryMenu extends javax.swing.JFrame {

    private ObjectInputStream in;
    private ObjectOutputStream out;
    private int currentCategoryId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryMenu.class.getName());

    /**
     * Creates new form Menu
     */
    public CategoryMenu(ObjectInputStream in, ObjectOutputStream out) {
        initComponents();
        this.in = in;
        this.out = out;
        displayCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("add category");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("delete category");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tên sản phẩm", "giá tiền", "id category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Current category:");

        jLabel2.setText("......");

        jButton3.setText("choose category");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("add food");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("delete food");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //add category
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String categoryName = JOptionPane.showInputDialog(null);
        if (categoryName == null || categoryName.trim().isEmpty()) {
            return;
        }
        try {
            CategoryFood category = new CategoryFood();
            category.setTen(categoryName);
            Request req = new Request("INSERT CATEGORY", category);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //delete category
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhập ID Category cần xóa");
        if (input == null || input.trim().isEmpty()) {
            return;
        }
        try {
            int categoryID = Integer.parseInt(input);
            CategoryFood category = new CategoryFood();
            category.setId(categoryID);
            Request req = new Request("DELETE CATEGORY", category);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayCategory(); //xóa xong hiển thị lại danh sách category
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID phải là số!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //chọn category
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn category!");
            return;
        }
        try {
            int categoryId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String categoryName = jTable1.getValueAt(row, 1).toString();
            currentCategoryId = categoryId;
            jLabel2.setText(categoryName);            
            displayFood(categoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //add food
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(currentCategoryId == -1){
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        try {
            String name = JOptionPane.showInputDialog(this, "Nhập tên món ăn:");
            if (name == null || name.trim().isEmpty()) return;
            String priceStr = JOptionPane.showInputDialog(this, "Nhập giá:");
            if (priceStr == null || priceStr.trim().isEmpty()) return;
            BigDecimal price = new BigDecimal(priceStr);
            Food food = new Food();
            food.setNameFood(name);
            food.setPrice(price);
            food.setIdcategory(currentCategoryId);
            Request req = new Request("INSERT FOOD", food);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayFood(currentCategoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jButton4ActionPerformed
    //delete food
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(currentCategoryId == -1){
            JOptionPane.showMessageDialog(this, "vui lòng chọn Category");
            return;
        }
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "C  họn món cần xóa");
            return;
        }
        try {
            int foodId = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            Food food = new Food();
            food.setId(foodId);
            Request req = new Request("DELETE FOOD", food);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            JOptionPane.showMessageDialog(this, res.getMessage());
            displayFood(currentCategoryId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    public void displayFood(int categoryId) {
        try {
            Request req = new Request("SELECT FOOD BY CATEGORY", categoryId);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            if ("SUCCESS".equals(res.getStatus())) {
                ArrayList<Food> list = (ArrayList<Food>) res.getData();
                for (Food f : list) {
                    model.addRow(new Object[]{
                        f.getId(),
                        f.getNameFood(),
                        f.getPrice(),
                        f.getIdcategory()
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, res.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void displayCategory() {
        try {
            Request req = new Request("SELECT CATEGORY", null);
            out.writeObject(req);
            out.flush();
            Response res = (Response) in.readObject();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            switch (res.getStatus()) {
                case "SUCCESS": {
                    ArrayList<CategoryFood> list = (ArrayList<CategoryFood>) res.getData();
                    for (CategoryFood c : list) {
                        model.addRow(new Object[]{
                            c.getId(),
                            c.getTen()
                        });
                    }
                    break;
                }
                case "NO_CATEGORY": {
                    JOptionPane.showMessageDialog(this, "Chưa có category nào!");
                    break;
                }
                default: {
                    JOptionPane.showMessageDialog(this, res.getMessage());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
